### ISSUE TITLE
Not possible to change primary key after release 3.0.0-rc.3

### ISSUE THREAD

**Issue by darkowic** [dfahlander/Dexie.js#996] opened 2020-03-18 16:16 UTC
I receive the following error:
```
UpgradeError: Not yet support for changing primary key
```
when trying to change primary key using  solution described https://github.com/dfahlander/Dexie.js/issues/88 and https://github.com/dfahlander/Dexie.js/pull/714/files#diff-148f19eef441b25cf3aaaf2a1cc6fda7R550

<details>
  <summary>Code example</summary>

```js
// In next version we need change primary key for slideThumbnail from slideId to autoincrement pk
// Version 3-6 migration
// See https://github.com/dfahlander/Dexie.js/issues/88
// https://github.com/dfahlander/Dexie.js/pull/714/files#diff-148f19eef441b25cf3aaaf2a1cc6fda7

export const SCHEMA_VERSION_3 = {
  __tmpSlideThumbnail: SCHEMA_VERSION_2.slideThumbnail
};

export const SCHEMA_VERSION_4 = {
  // delete old table
  slideThumbnail: null
};

export const SCHEMA_VERSION_5 = {
  // add again slideThumbnail and modify project to add editingId
  project: '&slug, lastModified, editingId',
  slideThumbnail: '[slideId+editingId], slideId, projectSlug, editingId, [projectSlug+editingId]'
};

export const SCHEMA_VERSION_6 = {
  // cleanup - delete temporary table
  __tmpSlideThumbnail: null
};
```

```js
  if (version > 2) {
    createdDB.version(3).stores(SCHEMA_VERSION_3).upgrade(async (transaction) => {
      const slideThumbnails = await transaction.slideThumbnail.toArray();
      await transaction.__tmpSlideThumbnail.bulkAdd(slideThumbnails);
    });
    createdDB.version(4).stores(SCHEMA_VERSION_4);
    createdDB.version(5).stores(SCHEMA_VERSION_5).upgrade(async (transaction) => {
      const editingId = Date.now();
      const slideThumbnails = await transaction.__tmpSlideThumbnail.toArray();
      await transaction.slideThumbnail.bulkAdd(slideThumbnails.map((thumbnail) => ({
        ...thumbnail,
        editingId
      })));

      transaction.project.toCollection().modify((project) => {
        project.editingId = editingId;
      });
      return transaction;
    });
    createdDB.version(6).stores(SCHEMA_VERSION_6);
  }
```
</details>

It is working for version `3.0.0-rc.2`.

**Comment by dfahlander** [comment] 2020-03-26 00:10
Duplicate of #1004

**Closed by dfahlander** 2020-03-26 00:10 UTC
