### ISSUE TITLE
Storage version gets increased but not all indexes are created

### ISSUE THREAD

**Issue by tp** [dfahlander/Dexie.js#100] opened 2015-05-20 14:43 UTC
For example, this is part of my storage definition:

```js
db.version(20)
      .stores({
cityIndex: 'id,displayName,*displayNameParts,isDeleted,countryRef,[countryRef+isDeleted],autoCreated,needsReview,[autoCreated+isDeleted],[needsReview+isDeleted],[autoCreated+needsReview+isDeleted],[autoCreated+countryRef+needsReview+isDeleted],[autoCreated+countryRef+needsReview+isDeleted],[autoCreated+robotsNoIndex+isDeleted],[autoCreated+needsReview+robotsNoIndex+isDeleted],[autoCreated+countryRef+robotsNoIndex+isDeleted],[autoCreated+countryRef+needsReview+robotsNoIndex+isDeleted]',
});
```

Those are by my count 17 indexes.

But not all of them get created, even though the version gets incremented in the browser.

Firefox: 13 / 17 indexes:
![screen shot 2015-05-20 at 16 41 26](https://cloud.githubusercontent.com/assets/52437/7728388/3f54e1d6-ff0f-11e4-96eb-c596871d4ed5.png)

Chrome: 15 / 17 indexes:
![screen shot 2015-05-20 at 16 42 58](https://cloud.githubusercontent.com/assets/52437/7728406/5283e108-ff0f-11e4-8bd7-13b1638c0df0.png)

Any ideas?

**Comment by dfahlander** [comment] 2015-05-20 14:50
Thanks for finding. I'll try to reproduce it in a unit test later on today.

**Comment by tp** [comment] 2015-05-20 14:53
@dfahlander Thanks. While this should definitely not fail silently, I now question my approach using all the compound indexes. I have read the article, that `.or` is quite performant, since it only operates on the primary keys.

Is `and` equally performant? Would you advise to switch from compound indexes to `and` for the highly variable queries?

**Comment by dfahlander** [comment] 2015-05-20 14:54
Nope. Compound indexes are the best pick for 'and' operations. The and() method is just a javascript filter.

**Comment by dfahlander** [comment] 2015-05-20 15:14
Found one possible issue: "[autoCreated+countryRef+needsReview+isDeleted]" is entered twice.

Still examining why it fails silently...

**Comment by dfahlander** [comment] 2015-05-20 15:54
Actually it is not failing silently if you've catched the db.open() call, or a subsequent call to use the database. It failed actually to open.

It's still an issue that the half-created database is still there and that the upgrade transaction is not aborted correctly, which I now trigger in a unit test and will resolve (not committed yet).

For your application though, just remove your duplicate index name "[autoCreated+countryRef+needsReview+isDeleted]". You might need to delete the database and recreate it because it was left in that half-upgraded state due to this issue.

**Comment by tp** [comment] 2015-05-20 16:09
Strange, I actually look for errors on db.open:

```js
db.open()
  .then(() => {
    console.log('opened the database');
  })
  .catch(function(error) {
    alert('Uh oh : ' + error);
  });
```

Since this is just a a development setup for now deleting the DB is no problem.

For future reference: Is inserting an empty intermediate version like this `db.version(23).stores({});` enough?

**Comment by dfahlander** [comment] 2015-05-20 16:31
It's not strange when I think about it. In my tests I always recreate the
db and get the error. The error only happens the first time. Once it has
happened, it will succeed on next open without complaining...
Den 20 maj 2015 18:09 skrev "Timm Preetz" <notifications@github.com>:

**Comment by dfahlander** [comment] 2015-05-25 06:00
I fixed the issue by always aborting the upgrade-transaction if any error occur. However, after running the unit test suite there has been some problems with other unit tests that I need to investigate.

**Closed** 2015-05-25 23:56 UTC
