### ISSUE TITLE
Safari 8 on MacOS X 10.10

### ISSUE THREAD

**Issue by andersekdahl** [dfahlander/Dexie.js#28] opened 2014-11-17 09:38 UTC
When trying to use Dexie on Safari 8 that now has IndexedDB support, you get an error saying `Dexie specification of currently installed DB version is missing`.

Have you had the change to test Dexie on Mac OS X/iOS?

**Comment by dfahlander** [comment] 2015-03-15 22:36
Closing this issue since the workaround for db version seems to be working fine with the fix. Still there are other issues with Safari but this particular issues was the one regarding the buggy version number in Safari's onupgradeneeded.

**Closed by dfahlander** 2015-03-15 22:36 UTC
Labels: needs testing!

**Comment by gitawego** [comment] 2015-06-29 16:01
I think it resolves but in safari, but breaks in chromium. I've nwjs v0.12.2 which uses Chromium 41.0.2272.76. 
Dexie throws error because the e.oldversion converted to 0.1 instead of 1.
![dexie_bug](https://cloud.githubusercontent.com/assets/438120/8412230/c26adbf0-1e88-11e5-9e26-d59bac271c5f.jpg)

**Comment by gitawego** [comment] 2015-06-29 16:09
nevermind, I came from another library, the old db version is set to 1 instead of 10.  :)
thanks for your great lib :+1:

**Comment by dfahlander** [comment] 2015-06-29 19:08
Yes, this is a wierd thing with dexie that version gets divided by 10. On the other hand, dexie wont fail with version 0.1 or 0.2, so it doesnt hurt. The issue is described in #59.
