### ISSUE TITLE
Specify temporary or persistent mode for indexeddb storage database

### ISSUE THREAD

**Issue by damoclark** [dfahlander/Dexie.js#467] opened 2017-01-31 04:51 UTC
Hi,

I've been searching the dexie API for a way to specify whether to use "best-effort" or "persistent" storage mode, but have been unable to.  Just wondering whether dexie supports this or not.

Details:
* [Storage Specifications](https://storage.spec.whatwg.org/#persistence)
* [Chrome Implementation](https://developers.google.com/web/updates/2016/06/persistent-storage)
* [Firefox Implementation](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria)

If this hasn't been implemented, it would be very useful to be able to specify the storage mode on creation of the database, and in an abstract way across browser implementations using Dexie.

Is this something that would be considered for the API?

Cheers,
Damien.

**Comment by dfahlander** [comment] 2017-01-31 08:49
Thanks for bringing this up. A natural place would be in the options to the Dexie constructor,  I suppose. Will look into the links and try finding an option name that corresponds to the standard. If you have any suggestion, you're welcome to share it. 

I suppose we will have to silently ignore the option for legacy browsers since it's not polyfillable, right?

**Comment by damoclark** [comment] 2017-02-01 03:23
Hey @dfahlander 

Thanks for responding.

> I suppose we will have to silently ignore the option for legacy browsers since it's not polyfillable, right?

Yes, that is my understanding.

The specification indicates the what, but not the how.  So just Firefox and Chrome alone implement the choice of mode in different ways.  This of course is the strength of something like Dexie where those differences can be abstracted through the Dexie API.  

I was thinking similarly - having the option in the Dexie constructor.  In fact, it is probably necessary to do this for the Firefox implementation as the storage mode is an option to the `open()` call for indexeddb.  But if anyone else has alternate suggestions and broader perspectives, it would be good.

In summary, Chrome calls a function on a globally scoped object to set the storage mode:

```javascript
if (navigator.storage && navigator.storage.persist)
  navigator.storage.persist().then(granted => {
    if (granted)
      alert("Storage will not be cleared except by explicit user action");
    else
      alert("Storage may be cleared by the UA under storage pressure.");
  });
```

While Firefox makes the mode an option on connection to the indexeddb database itself.

Standard:
```javascript
request = window.indexedDB.open(name[, version])
```

Experimental version (26+) with options:
```javascript
request = window.indexedDB.open(name[, options])
```

For instance:

```javascript
var request = indexedDB.open("myDatabase", { version: 1, storage: "persistent" });
```
or
```javascript
var request = indexedDB.open("myDatabase", { version: 1, storage: "temporary" });
```

With Firefox, I believe the difference is because you can have separate persistent and temporary storage for the same origin, but also the filesystem directory where the indexeddb storage is located in separated based on it being persistent or temporary.  

Hope this helps.

**Comment by sechel** [comment] 2017-07-04 08:35
This option would be appreciated. For us it is absolutely crucial to not lose data through UA eviction.

**Comment by dfahlander** [comment] 2017-07-08 03:44
Let's say we have a {persist: true} option in Dexie constructor, then it would generate a confirmation box on Firefox while failing or succeeding silently in Chrome.

As a webapp developer, I would (for some apps) care for not bothering the user under any circumbstances, and only try the persitent mode in case it can be done silently. Setting {persistent: true} would do that for Chrome but not Firefox as it would popup a dialog.

One suggestion would be to have three modes:
* {persist: 'default'}
* {persist: 'silent-best'}
* {persist: 'best'}

*(Naming suggestions welcome)*

I also think it would be necessary to have a property on the Dexie instance to know whether it was stored persistently or not.

```js
const db = new Dexie('appdb', {persist: 'silent-best'}); // or {persist: 'best'}
db.open().then(() => {
    console.log(`Do we have durable persistance?: ${db.isPersisted}`);
});
```

Would this do?

**Comment by dfahlander** [comment] 2017-07-08 04:28
Reading through the Chrome implementation of the standard proposal, it seems that performing the persist() request does not matter as the user-agent will automatically regard your site as persisted or not. This is not clear though, how this aught to work. I've tried to laborate with it on chrome but always fail to persist a site even though I've done "Add to desktop". Using chrome 60 beta. Anyone else that has been lucky with the Chrome API?

**Comment by sechel** [comment] 2017-07-08 20:09
Yes, on some of my test browsers the `persist` command succeeds. I guess it is the second of these four strange conditions that passes the test:  
* The site is bookmarked (and the user has 5 or less bookmarks
* The site has high site engagement
* The site has been added to home screen
* The site has push notifications enabled  

taken from here: https://developers.google.com/web/updates/2016/06/persistent-storage

However I always had to navigate to the origin directly and paste the commend into the console. What I really want is to invoke it from within an iframe (But that didn't work). All of our code that stores stuff to indexeddb runs in an iframe. Doesn't google explain these things rigorous somewhere else than in a blog post?

**Comment by sechel** [comment] 2017-07-08 20:14
> Reading through the Chrome implementation, it seems that performing the persist() request does not matter as the user-agent will automatically regard your site as persisted or not.
This is what I thought from reading the port the first time too. Reading it the second and third time it started to sound more like Chrome would decide in a totally non-transparent way after you invoked `persist`.

**Comment by dfahlander** [comment] 2017-07-09 05:14
Thanks @sechel for sharing your experience with the mysterious Chrome behavior. I've also been laborating with the Firefox behavior, which boils down to:
* Invoking indexedDB.open(dbname, {storage: 'persistent', version: 1}) the first time ever, will lead to a user prompt asking for permission.
* If by accident clicking "No" on that box, you will no more be asked ever(?). Each further call to indexedDB.open() with {storage: 'persistent'} will result in a DOMError "InvalidStateError".

So basically we would need to handle the Firefox state like this:
1. Try {storage: 'persistent'} and if successful, let db.persisted() return Promise.resolve(true).
2. If fails, re-run indexedDB.open() without {storage: 'persistent'} and let db.persisted() return Promise.resolve(false).

For chromium, I will need to code "in blind" (for now at least as I couldnt get it to work):
1. If using the Firefox-special indexedDB.open() results in an exception, assume browser is NOT firefox and try using navigator.storage.persist().
2. Let db.persisted() return navigator.storage.persisted()

**Comment by dfahlander** [comment] 2017-07-09 05:25
I'm thinking of having a simpler option `{persistent: true}` instead of the "silent" option. If a silent option will be added, we could accept `{persistent: 'silent'}`. This will be less error-prone as `{storage: 'persistent'}` could easily be spelled wrong so we would not have checks for option name.

**Comment by dfahlander** [comment] 2017-07-09 05:32
I'm not so keen on the term "persistent". I know the spec names it so, but for me, it would seem like `{persistent: false}` would mean in-memory only.

Maybe name the flag `{durable: true}` instead?

Comments appreciated! :-)

**Comment by sechel** [comment] 2017-07-09 17:39
I would call it `evictionPolicy` since that`s what it really is. It then can take the values `persistent` and `automatic`.

**Comment by sechel** [comment] 2017-07-09 17:45
Or if you don't like the strings then call it `{ automaticEviction: false }`.

**Comment by sechel** [comment] 2017-07-09 17:54
Speaking of Firefox, I tested `navigator.storage.persist` in Nightly and it did pop up the little frame with the question. And you can see and change you decision later in time. So there is some hope that eventually we will converge to something like a reasonable behaviour.
![bildschirmfoto 2017-07-09 um 19 51 54](https://user-images.githubusercontent.com/4698832/27996342-627d7f0e-64e0-11e7-99f6-7ae3adbd885c.png)

**Comment by dfahlander** [comment] 2017-09-22 21:23
I  case Firefox goes with the standard navigator.storage.persist() i see no direct need to implement this in Dexie. Maybe it's better to recommend people just calling something like
```js
await navigator.storage.persist  &&
 navigator.storage.persist();
const persisted = await navigator.storage.persisted && navigator.storage.persisted();
```

**Comment by dfahlander** [comment] 2017-10-30 10:44
Closing this as it is better to [provide samples and docs at dexie.org](https://github.com/dfahlander/dexie.js-web/issues/24) on how to use the [storage API](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager) with Dexie.js.

**Closed by dfahlander** 2017-10-30 10:44 UTC

**Comment by tanriol** [comment] 2017-11-02 11:09
@dfahlander There's the other side of this question: if you already have a "persistent" IndexedDB in Firefox, Dexie cannot open it in spite of what [the tutorial](http://dexie.org/docs/Tutorial/Migrating-existing-DB-to-Dexie) says and migration requires copying the data manually.

**Comment by dfahlander** [comment] 2017-11-02 12:43
@tanriol Thanks for your discovery. I opened a new issue #607 for this. Let's continue there.

**Comment by darkowic** [comment] 2019-02-08 14:01
I know that this is an old issue but how to make sure that your DB is using only persistent storage? Is there a way to force using persistent storage with its limitation if it exists? For example, I want to request only 20Mb of persistent storage and do not use any more available space.

**Comment by dfahlander** [comment] 2019-02-08 14:26
Have a look at https://dexie.org/docs/StorageManager. That API can be used to request persistent storage and query quota.

**Comment by dfahlander** [comment] 2019-02-08 14:33
Also have a look at the special way you need to catch this error in Dexie, as it may appear in the inner exception: https://dexie.org/docs/DexieErrors/Dexie.QuotaExceededError

**Comment by darkowic** [comment] 2019-02-08 15:09
The case is that I receive this error in sentry - `QuotaExceededError` and I want to limit the storage size to reproduce it and test it. I have read https://dexie.org/docs/StorageManager before asking this question. `StorageManager.persist` do not receive any argument... For now, I am stack (https://stackoverflow.com/q/54594173/5185634) but looks like someone just proposed something :)
