### ISSUE TITLE
Safari + where + modify = only one updated

### ISSUE THREAD

**Issue by nicolashenry** [dfahlander/Dexie.js#594] opened 2017-10-16 16:11 UTC
I am doing somthing like this in an async function : 
```ts
console.log((await table.where('objectProperty').equals(myValue).toArray()).length);
console.log(await table.where('objectProperty').equals(myValue).modify((object) => { object.anotherProperty = 'test'; }));
```
I have 3 objects matching 'myValue' for 'objectProperty'.
Chrome displays:
```ts
3
3
```
Safari displays:
```ts
3
1
```
So it modifies only one entry on Safari (v11 with Dexie 2.0.1). I tried multiple changes on my code to make it work, the only thing which works was to loop on each array value and update each entry one by one.

**Comment by dfahlander** [comment] 2017-10-16 16:24
Thanks for the finding. Some questions just to nail it down:
* Are you using binary keys (ArrayBuffer, etc)?
* Are you using CRUD hooks?

**Comment by dfahlander** [comment] 2017-10-16 16:25
Also, is Safari 11 in beta still? Do you see the same issue in Safari 10?

**Comment by nicolashenry** [comment] 2017-10-16 16:26
I am using a number key and I am using CRUD hooks.

**Comment by nicolashenry** [comment] 2017-10-16 16:30
I think Safari 11 is not in beta anymore, I never installed a beta version as far as I remember.

**Comment by nicolashenry** [comment] 2017-10-16 16:37
Note that it also happens on iOS Safari v11.

**Comment by nicolashenry** [comment] 2017-10-16 17:06
I tried to not use CRUD hooks but it does not seems to change anything. I think I can't downgrade Safari to version 10 sadly.

**Comment by dfahlander** [comment] 2017-10-16 17:08
Ok thanks. I'll try repro it on Safari 10 later this evening.

**Comment by dfahlander** [comment] 2017-10-16 22:19
Confirmed there is an issue with Safari (10 and 11). If iterating an index (Dexie where()) the object being iterated must never be modified. This does not apply when iterating an entire object store (db.table.toCollection().modify()) - just when iterating an index (db.table.where(...).modify()).

We could work around this issue in Dexie by modifying the items first when the iteration has completed, but it would be be a larger effort and could possibly affect the behavior of Colletion.modify() in some rare use cases.

For now, we need to announce this and propose a workaround.

**Comment by dfahlander** [comment] 2017-10-16 22:30
Proposed workaround:

```js
async function modify (collection, modifyerFn) {
  const objectsToModify = await collection.toArray();
  objectsToModify.forEach(obj => {
    modifyerFn(obj);
  });
  await table.bulkPut(objectsToModify);
  return objectsToModify.length;
}


// Example use:
const numMofidied = await db.transaction('rw', db.friends, ()=>modify(db.friends.where('age').above(64),
    friend => friend.retired = true
));

```

**Comment by dfahlander** [comment] 2017-10-17 07:43
Filed in webkit buzilla: https://bugs.webkit.org/show_bug.cgi?id=178380

**Comment by nicolashenry** [comment] 2017-10-17 09:00
The workaround seems to work for now, thanks!

**Comment by dfahlander** [comment] 2017-10-24 09:44
I think we will need to fix a Safari-workaround for this issue in Dexie as [Collection.modify()](http://dexie.org/docs/Collection/Collection.modify()) is a quite central part of the library. I'll see what I could do about it.

**Comment by jokamax** [comment] 2017-11-02 07:01
Hi,
Horrible bug...
It concerned Chrome under IOS 11 too (webkit) ? It seem touch some users on my side with this configuration.

Do you think integrate a workaround soon directly in dexie or you advise to use the workaround above (many and many modify in my application - hierarchical menu offline ;) )?

Thanks a lot,

Jonathan

**Comment by dfahlander** [comment] 2017-11-02 08:45
Yes it's sad because in all other aspects Safari has got an almost a perfect IndexedDB implementation. My goal now is to implement a workaround as soon as possible, but can't promise when it will be released. If you do a workaround similar to the one mentioned in this issue, it should be almost identical to the workaround I'm planning to do with one caveat: If your Collection targets thousands of large objects, the workaround could suffer from large memory consumption. The final workaround that will be implemented in Dexie.js will try to avoid large memory consumption in those cases (by splitting into chunks). Otherwise, it will be almost identical.

**Comment by jokamax** [comment] 2017-11-02 09:10
Thanks for the quick reply. 
I have to think about it...
(for the moment it concern around 20 users on 500, but I have to change the remote MySql copy every day by hand their menu... Maybe I will ask them to use firefox for the moment)

**Comment by jokamax** [comment] 2017-11-02 13:42
Hi (again), 

I'm not a specialist of ES7/8 but it there a way to write a proposal workaround without async/await (Safari 9, Chome < 50 et FF < 50 compatible) ?

Thanks,

Jonathan

**Comment by nicolashenry** [comment] 2017-11-02 13:54
You can try this:
```js
function modify(collection, modifyerFn) {
  return collection.toArray()
  .then(function (objectsToModify) {
    objectsToModify.forEach(obj => {
      modifyerFn(obj);
    });
    return table.bulkPut(objectsToModify)
    .then(function() {
      return objectsToModify.length;
    });
  });
}
```

**Comment by jokamax** [comment] 2017-11-03 15:30
It works like a charm !

**Comment by dfahlander** [comment] 2017-11-04 21:16
There's another workaround that enables the use of Collection.modify().

```js

```js
draft.where('pj_id').equals(pj_id).and(function (draftFilter) {
    return (draftFilter.bg >= targetItem.bg && draftFilter.bd <= targetItem.bd);
  }).primaryKeys().then(function (keys) {
    return draft.where(':id').anyOf(keys).modify (...)
```

This version is not as fast as the other workaround but it should support using existing callbacks to modify. I've not tested it though but if someone with a Mac could verify it that would be awesome ;)

**Comment by dfahlander** [comment] 2018-03-03 22:03
@beidson Just want to ping you again for an update of [new Safari-related issue](http://dexie.org/docs/IndexedDB-on-Safari#safari-version--101-and-110) and found that two of them stands out more than the others (imho); this one (#594) but also #656. Just for your info. [The webkit bug report](https://bugs.webkit.org/show_bug.cgi?id=178380) for this one is still at state *NEW*. Would be awesome if you could have a look ;)

Kind regards, David

**Comment by jokamax** [comment] 2018-04-16 10:08
@dfahlander just a question.
This bug concern "modify". 
No problem with Table.Where(toto: toto).delete() ? I ask because in the documention delete can be written with modify.

Thanks by advance,

Jonathan

**Comment by dfahlander** [comment] 2018-04-16 20:38
delete() does not use modify anymore, so no, it should not be affected.

**Comment by jokamax** [comment] 2018-04-16 20:42
Thanks a lot

**Comment by dfahlander** [comment] 2018-11-08 09:08
That's good news. Dexie update: Latest alpha version of Dexie (dexie@3.0.0-alpha.5) works around the Safari issue already in it's implementation of Collection.upate(). Maybe late in the game then... But anyway I hope the redesign both improves performance and works around the issue for Collection.modify.

**Comment by jokamax** [comment] 2019-02-14 10:10
@dfahlander Excuse me I just want to be sure : 
Since dexie@3.0.0-alpha.5 ==> I haven't to use "cheat" function modify by myself anymore ? A pseudo patch inside this alpha ?

**Comment by dfahlander** [comment] 2019-02-14 10:39
@jokamax Yes, Collection.modify() works as expected on Safari 10+. To be certain, I just now enabled an old remarked unit test that triggered the error. Manually verified that it's actually solved (tested with Safari 10 and Safari 12). Let's see also that the automated tests pass in a few minutes.

**Comment by jokamax** [comment] 2019-02-14 14:19
@dfahlander Just a big big thanks !

**Closed** 2019-03-08 09:41 UTC
Labels: browser bug
