### ISSUE TITLE
Promise redeclaration / async incompatible with Typescript 2.0

### ISSUE THREAD

**Issue by cherrydev** [dfahlander/Dexie.js#315] opened 2016-09-20 01:18 UTC
As of Typescript 2.0 (or possibly 1.9, I never tested it there) declaring a top-level `let Promise = Dexie.Promise;` results in:

`Duplicate identifier 'Promise'. Compiler reserves name 'Promise' in top level scope of a module containing async functions.`

While before, using async after redefining Promise was already only marginally useful with Dexie because the redefinition had to go all the way up the call chain to the top-level 'async', it looks like the Typescript team finally closed this hole that allowed this to work.

Furthermore, the other suggestion in the documentation to redeclare Promise in an inner scope doesn't work, resulting in `IncompatiblePromiseError: Incompatible Promise returned from transaction scope (read more at http://tinyurl.com/znyqjqc).`

It appears that redefining the global Promise constructor with Dexie.Promise works, but will make it impossible to localize the changes to just a particular module or global block of code and will completely break Angular2 (which relies on ZoneJS patching the native Promise implementation).

I'm a bit concerned about the long-term viability of Dexie relying on a custom Promise implementation to allow transactions to work. The apparent goal of the transaction system is to allow transactions to span transparently between blocks of code that have specific knowledge of Dexie and portions that don't but if at any point in that chain a Dexie Promise gets wrapped (`Promise.resolve()`) or aggregated (`Promise.all()`) in a native Promise, it breaks. Zone.js appears to offer everything that is needed for Dexie to implement transactions, but without having its own separate Promise implementation (instead it patches an existing Promise implementation).

I only have a limited amount of time within my own project to try to figure this out, but if there are, in fact, ways of getting Dexie transactions to span multiple modules in the way that I've described, using Typescript 2.0, ES7-style async/await and Angular 2, I'd be very, very interested in seeing a demonstration of it.  For now, I appear to be limited to using Dexie without async/await and without having any Dexie operations cross any Promise wrapper/aggregation boundary.

**Comment by dfahlander** [comment] 2016-09-22 09:01
I'm not saying this is the best solution, but it should be possible to replace window.Promise with Dexie.Promise before Zone.js starts wrapping stuff. If you try this out, I believe you would need to include dexie.js as a plain script tag before anything else, and set window.Promise = Dexie.Promise. Then include zone.js and the rest.

## Long term code sustainability

When reading the Typescript issues about this, it seems they plan to loosen this strategy in a year or two. So it seems this will probably be possible in a future version of Typescript as long as they continue transpiling async functions to spawn/yield.

If there will come a day when Typescript stops transpiling async function (when asyncawait is natively supported across all browsers), we could get into a problem if indexedDB is still incompatible with native promises at that time. You would also be dependent on that Dexie, at that time, will adapt to native Promises, which I have a plan to do.

## Summary

Two things itches with async / await:

1. Replacing window.Promise with Dexie.Promise is an ugly solution, even though it should work out technically if doing it before Zone.js kicks in.
2. Long term code sustainability is at risk because browser-native async/await is tied to native Promise which means you'll be depending on two things: A) #317 is resolved in Dexie. B) IndexedDB across all your target browsers will start to play ball with native promises.

Due to these questions, it is probably better to stop using async / await and go back to promise-style database code within transactions.

**Comment by cherrydev** [comment] 2016-09-22 17:48
https://github.com/angular/zone.js/issues/455 indicates to me that your proposed solution won't work since if that approach doesn't work with Bluebird, I don't see it working with Dexie's promises either.

**Comment by dfahlander** [comment] 2016-09-22 19:25
Aha, so zones replaces Promise entirely... Didn't know. But I'm not sure that has to be a problem since Dexie will only use Dexie.Promise internally which is not replaced.

Anyway, the ES7 async await when implemented natively won't respect changing window.Promise according to the spec.  It'll still use the native Promise no matter. And as I understand it, there will be no way to hook in to the asynchronous callback when an await returns so zonejs won't be able to do its job either. I might be wrong but this is how I interpret the spec. Would be interesting to test with the Edge browser that has already implemented async await natively.

**Comment by cherrydev** [comment] 2016-09-22 22:54
While I won't pretend this is a completely sound argument, I very strongly believe that somehow, Google has the clout to ensure that Angular2 (which is fundamentally dependent on the concepts that zones provide) will not be left out in the cold when the ES7 spec solidifies. If this were my project, I would feel confident that a Dexie transaction implementation that was built on top of zones instead of custom Promises would be a reasonable long-term risk since the implications of ES7 fundamentally breaking zones would be so big.

And yes, I had already tried globally replacing Promise with Dexie.Promise and `Zone.assertZonePatched` caught me red handed.

Btw, Zones are already a proposed (stage-0) addition to ES7 meaning the exact semantics of ES7 async/await might be completely moot on that matter. https://github.com/tc39/proposals/blob/master/stage-0-proposals.md
It looks like the ES7 Zone proposal is ready to present to the committee but has not done so yet.

**Comment by dfahlander** [comment] 2016-09-22 23:05
I see what you mean. However,  I would not want to depend on zonejs. But I could consider ride upon it as an option. But still, indexedDB and native Promise does not cope anyway for the coming years in Firefox, ie, Edge and Safari so Dexie.Promise will still be need even if I use zonejs for keeping the reference to the transaction.

**Comment by dfahlander** [comment] 2016-09-23 10:40
Ok, so I've played around a little and made a branch that supports native promises without having to wrap stuff in Dexie.Promise. This turns out to work with native async await in Edge. It will most likely work on in typescript 2.0 as well.

However, the incompability between indexedDB and native promises in Edge, Safari and Firefox persist, so using async await (or Promise.all() etc) will still fail in Edge, Safari and Firefox with TransactionInactiveError, as I already knew. This fix may only be useful for developers targeting Chromium exclusively.

If you have the posibility, checkout my new branch 'experiment/support-native-promise' and test it in angular / zone.js to see if it copes with zone.js as well.

You can easily make your app use that branch using npm link and npm link dexie, see https://github.com/dfahlander/Dexie.js#contributing.

**Comment by dfahlander** [comment] 2016-09-30 12:40
I think I've actuallt solved this issue, keeping indexedDB compliance in async/await in Typescript, Babel and Zone.js. The fix is so far only committed to the "develop" branch. It would be nice if someone could test this with Typescript 2.x + Zone.js.

### db.tranx()
A new alternative to db.transaction() that will create a transaction scope where the global Promise is replaced with Dexie.Promise. The effect of this is the following:

* Typescript async/await should just work
* Babel async/await should work
* Should play well with Angular2 and Zone.js
* Users would not have to care for using Dexie.Promise instead of just Promise within transactions anymore.
* db.tranx() will restore the original window.Promise whenever leaving the transaction scope, so the rest of your app won't be affected by the Promise change. You could use native Promise, Promise polyfill, bluebird or whatever. The only thing to keep in mind is that accessing Promise withing a transaction scope will give you Dexie.Promise so you wouldn't be able to use for example bluebird's extended methods within the transaction. Only outside the transaction.

```js
db.tranx('r', db.friends, db.pets, function() {

    // WITHIN SCOPE. window.Promise === Dexie.Promise

    return db.friends.where('name').equals('David').first(function(friend) {

        // WITHIN SCOPE. window.Promise === Dexie.Promise

    });

    setTimeout(function() {

        // NOT WITHIN SCOPE! (window.Promise === the original global Promise)

    }, 0);

}).then(function() {

    // Transaction committed. NOT WITHIN SCOPE. window.Promise === original Promise

}).catch(function(err) {

    // Transaction aborted. NOT WITHIN SCOPE. window.Promise === original Promise.

});
```

**Comment by cherrydev** [comment] 2016-09-30 17:34
I've just started on a sabbatical of sorts for at least the next month, so I'm not able to follow up on this for quite some time. Good luck with it, though and I'll be in touch if I get back to this portion of the project.

**Closed** 2016-10-11 23:21 UTC

**Comment by dfahlander** [comment] 2016-10-12 12:42
[Dexie 2.0.0 beta](https://github.com/dfahlander/Dexie.js/releases/tag/v2.0.0-beta.2) should work with Typescript 2.0 async function within transactions.

```
npm install dexie@next
```

**Comment by dfahlander** [comment] 2016-10-19 13:03
Confirmed that it works now with Typescript 2.1: 

https://github.com/dfahlander/Dexie.js/tree/master/samples/typescript

**Comment by wwoods** [comment] 2016-10-22 05:57
Testing this out with Typescript 2.1 / Dexie 2.0.0 beta.

I'm not sure if I'm calling the transaction wrong or not, but I keep getting "TransactionInactiveError: Transaction has already completed or failed" when using async functions with Dexie.transaction; my code is something like below:

```ts
let d = new Dexie("Test");
//init, set up tables...
d.transaction('r', d.table, async () => {
  //Not sure if this is significant, but in my code I await on an fs routine before dealing with db
  await fs.open(...);
  await fs.write("header");
  for (let table of d.tables) {
    await table.each(async (o) => {
      await fs.write(JSON.stringify(o));
    });
  }
});
```

Am I using the function wrong?  If not, I can try to make a self-contained .ts script that reproduces the error.

**Comment by dfahlander** [comment] 2016-10-22 09:22
You need to transpile to target es5 and don't involve babel,  see the updated typescript sample in the repo.

**Comment by dfahlander** [comment] 2016-10-22 09:42
Ok,  I just read your code more carefully. It fails due to calling other async api within transaction. See https://github.com/dfahlander/Dexie.js/wiki/Best-Practices#3-dont-use-other-async-apis-inside-transactions

**Comment by dfahlander** [comment] 2016-10-22 09:43
Tips is to call the other api before entering the db transaction

**Comment by wwoods** [comment] 2016-10-22 15:06
Oh it's an indexed db thing?  That's really strange...  Is there any sort of noop Dexie could do for the user when the promise hasn't returned?  Something to keep the transaction alive?  How is a tick defined here, just as one db operation?

If nothing can be done, I would suggest maybe putting a quick message about not missing a tick into the error message for a closed transaction.

**Comment by wwoods** [comment] 2016-10-22 15:14
For example, since several db promises can run in parallel, would it be possible to, when a promise is seen to be the result of the scopeFunc, to spawn a secondary promise that constantly queries nothing... Or iterates table names... Or something.  Then have that promise loop until a variable is flipped on completion of the scopeFunc promise.

Since such an approach might affect performance, maybe have a flag in transaction() or a differently named transaction function altogether for this functionality?

Regardless of fs in my case, I'm sure other users will want to read/write in a transaction and make URL calls in between based on data read.  As you said, it's best to do so outside of a transaction, but not always possible.  e.g. for dumping the database in a consistent state (my use case).  An officially supported workaround would be very nice.

**Comment by wwoods** [comment] 2016-10-22 15:45
So, my code works fine if I do:

```ts
    let adapt = (a) => {
      return () => {
        let done = false;
        let busy = async () => {
          while (!done) {
            await this.tables[0].count();
          }
        };
        let r = a();
        r.then(() => {done = true;}, () => {done = true;});
        return busy();
      };
    };
    d.transaction('r', d.table, adapt(async () => {
      ...
    }));
```

Again, having a wrapper like this as an option on the Dexie object would be really nice for this situation.  Also, the error message might want to mention the IndexedDB limitation.

Thanks again for all of your work on this project, hope that's helpful to you.

**Comment by wwoods** [comment] 2016-10-22 16:03
I see.  Looks like each promise has to have activity each tick to not get shut out of the database.  The Table.each() promise would never return in the non-busy thread.  Annoying, but not much you can do.  Thanks for the help

**Comment by dfahlander** [comment] 2016-10-23 00:13
It would be possible to implement readonly db snapshots that persist over transactions, but it would be cumbersome. (using crud hooks that record changes and emulate db api). 

There is also a [new proposal](https://github.com/inexorabletash/indexeddb-promises/) going on to enhance indexedDB with a IDBTransaction.waitUntil(promise).  Would solve the issue. But it's far future :(

**Comment by dfahlander** [comment] 2016-10-23 00:14
Using noop would be possible as well but it would have to be flagged for due to performance reasons.

**Comment by wwoods** [comment] 2016-10-23 00:40
Just to clarify, I tried having a noop thread work alongside the thread that was alternating `fs` and `Dexie.Table` calls.  Although Dexie didn't raise an error anymore, the code did not work either, presumably because each promise "thread" needs to have `indexedDB` activity each tick to stay active.  That's why I changed to two promise threads, a file writer and a db reader.  The db reader just reads as fast as it can, and the file writer checks the buffer periodically and swaps it out / writes what was read to disk.  It's effective, but not generalizable to a single async call with both non-`Dexie` and `Dexie` awaits.

So, I don't think the noop is feasible, unless you got really fancy and replaced all of `Dexie`'s methods with versions that basically filled a work queue for the noop thread, which then ran those methods.  Sounds very obfuscated and slow.... but I guess it would work.
