### ISSUE TITLE
Version rollback after db.open() if page reloading took place. Bug!

### ISSUE THREAD

**Issue by Polenov** [dfahlander/Dexie.js#64] opened 2015-02-04 11:05 UTC
Found a bug. db.open() gets previous version of db if the page was reloaded.
At the first picture my code works as described below. Dexie object will be initialised only once and the structure of db might be modified many times successfully. I always can get the actual version after db was opened in the part 2. 
![db1](https://cloud.githubusercontent.com/assets/10111595/6039063/c3452f7e-ac84-11e4-919e-33e1ca25692c.jpg)
But if I reloaded the page, then new Dexie object will be created. So I can't get the actual version after db.open() in the part 2. Before I run db.open() in the part 2, my db.verno == version, but right after db was openned, my db.verno == version -1. So I can't change db structure anymore after page reloading. This situation is described at the second picture.
![db2](https://cloud.githubusercontent.com/assets/10111595/6039064/c345ff3a-ac84-11e4-9ce3-63f5f4769232.jpg)
I understand that it is really hard to explain my situation, but I tried. If you need more details, please ask. Hope it is possible to fix.

**Comment by dfahlander** [comment] 2015-03-15 22:29
Thanks for your effort to describe this issue. Still it is hard to understand what is going wrong without a full sample code. Could you link to a jsfiddle or attach a page that reproduce the error? I will do my best to try find the eventual bug. Thanks in advance! // David

**Comment by Polenov** [comment] 2015-04-01 03:53
Our company decided to use raw IndexedDB API, so that code doesn't exist nomore. 
The main idea in my issue was in fact that I got the previous version after page refreshing, not the last.

**Comment by dfahlander** [comment] 2015-04-01 17:59
Closing this issue because we cannot reproduce it and it's not occurring in our unit tests (test-upgrading).

**Closed by dfahlander** 2015-04-01 17:59 UTC
