### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by davehall81** [dfahlander/Dexie.js#291] opened 2016-07-12 15:40 UTC
Typescript definition file does not allow subscribing to table events if the subscriber defines any expected variables, example:

`this.local.hook('reading', (item:any) => { // some func });`

Will fail typescript compilation due to the above hook function having defined a parameter to receive, this is because the typescript definition file defines the hook function as having no parameters where in fact it should have some. A simple, though crude, fix would be to define hook functions as having any number of variables like shown below:

```
interface Table<T, Key> {
        ....
        hook: {
            (eventName: string, subscriber: (...vars:any[]) => any): void;
            ....
        }
        ....
}
```

instead of what it is currently:

```
interface Table<T, Key> {
        ....
        hook: {
            (eventName: string, subscriber: () => any): void;
            ....
        }
        ....
}
```

I can submit a pull request for this if desired, though I am not sure of the project structure and therefore of where I should apply the fix, I assume in the src folders Dexie.d.ts though?

**Comment by dfahlander** [comment] 2016-08-19 12:36
Thanks for the input. Here's a late response since I've been away for awhile. It's the src/Dexie.d.ts that is the source and that should be patched, yes! Your very welcome to do a pull request if you're still on it. Thanks! /D

**Comment by dfahlander** [comment] 2016-10-19 13:07
Duplicate of #347

**Closed by dfahlander** 2016-10-19 13:07 UTC
