### ISSUE TITLE
Unhandled rejection warning when using await syntax with babel

### ISSUE THREAD

**Issue by blastrock** [dfahlander/Dexie.js#729] opened 2018-07-10 13:40 UTC
Here is a small test:

```js
    const db = new Dexie('test', { autoOpen: true });
    db.version(1).stores({
      tab: "++id",
    });
    db.close();
    try
    {
      await db.table('tab').get(1);
    }
    catch (e)
    {
      console.log("database has been closed");
    }
```

The catch section is correctly run, but I get the following log in the console:

```
Unhandled rejection: DatabaseClosedError: Database has been closed
    at tempTransaction (http://0.0.0.0:9876/base/src/__tests__/index.js?293c231bb00ace5a053302245caaf64fb605952f:32084:38)
    at Table.getTransaction (http://0.0.0.0:9876/base/src/__tests__/index.js?293c231bb00ace5a053302245caaf64fb605952f:32588:17)
    at Table.getIDBObjectStore (http://0.0.0.0:9876/base/src/__tests__/index.js?293c231bb00ace5a053302245caaf64fb605952f:32597:25)
    at Table.get (http://0.0.0.0:9876/base/src/__tests__/index.js?293c231bb00ace5a053302245caaf64fb605952f:32609:25)
    at Context.it.only (http://0.0.0.0:9876/base/src/__tests__/index.js?293c231bb00ace5a053302245caaf64fb605952f:106993:29)
    at callFn (http://0.0.0.0:9876/absolute/home/philippe/work/tanker/Web/node_modules/mocha/mocha.js?57fe3557ec3449958ea3a5925bc668dd9691de11:4490:21)
    at Test.Runnable.run (http://0.0.0.0:9876/absolute/home/philippe/work/tanker/Web/node_modules/mocha/mocha.js?57fe3557ec3449958ea3a5925bc668dd9691de11:4482:7)
    at Runner.runTest (http://0.0.0.0:9876/absolute/home/philippe/work/tanker/Web/node_modules/mocha/mocha.js?57fe3557ec3449958ea3a5925bc668dd9691de11:4996:10)
```

The warning is silenced if I use .catch, but it's not very convenient:

```js
      await db.table('tab').get(1).catch(() => { console.log("database is closed"); });
```

**Comment by dfahlander** [comment] 2018-07-11 15:22
After an explicit close of database, you will have to open it explicitly. The option {autoOpen: true} (which is the default, by the way), only assures that a fresh instance will auto-open, not a closed one.

So what you need to do is call db.open() after db.close().

```js
const db = new Dexie('test', { autoOpen: true });
db.version(1).stores({
  tab: "++id",
});
db.close();

try
{
  await db.open(); // Reopen needed if database was closed.
  await db.table('tab').get(1);
} catch (e)
{
  console.log("database has been closed");
}
```

**Comment by blastrock** [comment] 2018-07-11 16:13
Sorry, my bug report may have been unclear. The `close()` was intentional, my problem is not the error itself, it is the fact that a warning is logged on the console even though the error is handled by my code.

**Comment by dfahlander** [comment] 2018-07-11 22:14
I see! Thanks for the bug report. I'll see what could be done. Wonder if all exceptions behave the same. For example a trying to get a boolean (invalid type) instead of a number, or trying to add an item that already exists. From what I remember, async try...catch should silence that log output generally. But it could be revisited.

**Comment by dfahlander** [comment] 2018-07-12 05:41
As a poor workaround unhandled rejections can be silenced using the following:

```js
window.addEventListener('unhandledrejection', ev => {
  if (ev.reason.name === 'DatabaseClosedError') {
    ev.preventDefault();
  }
});
```

**Comment by blastrock** [comment] 2018-07-12 08:09
A small hint: in dexie's get function, the end of the return statement is `}).then(cb);`. In my case, cb is undefined. If I remove the then(cb), the warning is silenced.

**Comment by darkowic** [comment] 2018-11-05 09:20
This is very annoying when you want to work with async/await API. I do not want to use then/catch because it will quickly lead to callback hell :) What is the source of the problem? Why async/await does not catch the error properly?

**Comment by dfahlander** [comment] 2018-11-05 13:14
I was able to reproduce this. Detecting unhandled rejections fails when converting an immediately rejected Dexie.Promise to a native Promise.

What I can do in the short term, is to silence default console warnings as long as `Dexie.debug` is falsy. In the long term, I want to remove the proprietary promise handling and rely on the native behavior of unhandled rejections with some polyfills for older browsers instead.

What the unit test shows, is that this warning only happens on immediate promise rejections (when arguments are faulty (such as DataError due to wrong key type Table.get(boolean)) but never happens from the result of the state of the data (such as ConstraintError due to adding an object with duplicate key). So basically when seeing this warning, it can also be worked around in application code by not providing faulty arguments to the Dexie API.

**Comment by dfahlander** [comment] 2020-02-11 10:21
Closing this as there is a way to turn if off using `Dexie.debug = false`, see https://dexie.org/docs/Dexie/Dexie.debug

**Closed by dfahlander** 2020-02-11 10:21 UTC
Labels: bug
