### ISSUE TITLE
Store/table not dropped if not exist on new stores version

### ISSUE THREAD

**Issue by nevcos** [dfahlander/Dexie.js#260] opened 2016-06-02 17:47 UTC
Stores/tables are not being dropped/removed when the new stores version removes some store.

[Documentation](https://github.com/dfahlander/Dexie.js/wiki/Design#database-versioning) tells that:
> If a previous version is installed, Dexie will filter out the diff between each version and add/remove stores and indexes sequencially. So also with any registered upgrader function

On the next example, "monsters" should not exist on version 2, but store still exists:
https://jsfiddle.net/nevcos/d1x5wyj4/

Tested with Dexie 1.3.6.

**Comment by dfahlander** [comment] 2016-06-02 20:29
It's actually by design. But when I try googling my own doc, I can't find where it's documented even though I recall I've documented it. To delete a table, one must specify null. The purpose of this is when having lots of tables and just changing one of them, it's a bit cumbersome having to repeat all of them. So it's ok to just specify the changed table schemas. So in your sample, it should be :

```js
db.version (2).stores({
  cats: 'id',
  dogs: 'id',
  monsters: null
});
```

**Comment by nevcos** [comment] 2016-06-03 09:44
Cool! So it's just a documentation issue.

Thanks and congrats about this great project!

**Comment by dfahlander** [comment] 2016-06-07 10:00
Updated docs https://github.com/dfahlander/Dexie.js/wiki/Design#database-versioning

Closing issue.

**Closed by dfahlander** 2016-06-07 10:00 UTC
