### ISSUE TITLE
dexie-encryped query data that has not been encrypted before will report an error

### ISSUE THREAD

**Issue by baobao12356** [dfahlander/Dexie.js#1373] opened 2021-08-04 09:04 UTC
I use dexie-encryped to query data that has not been encrypted before, and an error will be reported. The error message is Error utf8: invalid string, as shown in the figure below. How to solve it?
![image](https://user-images.githubusercontent.com/22005273/128153780-b5452896-f1ce-4c92-9fd9-7f24279bad7e.png)

**Comment by dfahlander** [comment] 2021-08-04 09:16
Duplicate of https://github.com/mark43/dexie-encrypted/issues/32

**Closed by dfahlander** 2021-08-04 09:16 UTC
