### ISSUE TITLE
Dexie2 with Webpack2 is incompatible with ES5

### ISSUE THREAD

**Issue by dpogue** [dfahlander/Dexie.js#466] opened 2017-01-30 23:25 UTC
Webpack 2 supports ES6 modules and uses the `module` field in package.json to look for a module-ized version of the source files. It does not do any transpiling of the files that it finds.

Dexie 2.0.0-beta.9 provides a full ES6 version in its `module` field, which results in Webpack bundling files that aren't compatible with ES5 browsers. The TypeScript .d.ts also requires full ES6 support enabled due to Iterables and `Symbol.toStringTag`.

This effectively means we have to choose between Webpack 2 and Dexie 2, or figure out how to blacklist loading Dexie with ES6 modules in our Webpack config.

I'm not sure what the best solution here is... Webpack and Rollup's guidelines are to [publish and point to ES5-compatible code](https://github.com/rollup/rollup/wiki/pkg.module) using only the ES6 module syntax in the `module` field.

**Comment by dfahlander** [comment] 2017-01-30 23:46
This is mostly a duplicate of #460. The typings issue is fixed using:
```
"lib": ["dom", "es2015"]
```
in tsconfig.json. Dexie does not depend on any runtime es6 feature but used some when available (such as toStringTag, Symbol and Iterators)

**Comment by dpogue** [comment] 2017-01-30 23:48
It looked like Dexie was using `const` which was causing errors in PhantomJS.

**Comment by dfahlander** [comment] 2017-01-30 23:56
Next release will have #460 fixed so there will be no const in the dist version. If it's a showstopper we could release it asap.

**Comment by dpogue** [comment] 2017-01-31 00:04
No rush, was just testing out the beta :)

**Comment by dfahlander** [comment] 2017-01-31 10:23
Thanks for testing it out 🥇  Resently released beta 10. If you have a change, please try it and see if it resolves the issue. Closing for now, feel free to reopen!

**Closed by dfahlander** 2017-01-31 10:23 UTC

**Comment by dpogue** [comment] 2017-01-31 21:02
I can confirm beta 10 works :)

**Comment by sebastien-roch** [comment] 2017-06-29 09:23
I'm having the same issue, the beta 11 does not work for me. Here is my tsconfig:
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "strictNullChecks": true,
    "noImplicitAny": false,
    "outDir": "./dist/",
    "sourceMap": true,
    "target": "es5",
    "module": "commonjs"
  },
  "lib": ["dom", "es2015.promise", "es5"]
}
```

I get the error: `ERROR in \Some\project\node_modules\dexie\dist\dexie.d.ts
(134,19): error TS2304: Cannot find name 'Symbol'.`

I tried changing `lib` to `["dom", "es2015"]` , that doesn't help.
Using Typescript 2.4.1.

Thanks for your help.

**Comment by nponiros** [comment] 2017-06-29 17:12
@sebastien-roch put `"lib": ["dom", "es2015"]` into compilerOptions.

**Comment by sebastien-roch** [comment] 2017-06-30 19:58
@nponiros oh my... thanks, that did the trick! (but I'm surprised Typescript didn't catch that)
